import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { QuizProvider } from "./contexts/QuizContext";

const soraSans = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${soraSans.variable} antialiased relative`}>
        <div className="absolute inset-0 bg-[url('/images/backgrounds/bg_yellow.webp')] bg-cover blur-md opacity-16" />
        <QuizProvider>{children}</QuizProvider>
      </body>
    </html>
  );
}
